### PR TITLE
Support for Fly 2

### PR DESCRIPTION
**Pull request by otariidae**
Changes:
- Upgrade to [the new syntax](https://github.com/flyjs/fly/tree/v2.0.3#external-plugins)
- Add `try...catch` and emit `plugin_error`
- Improve a test with real Fly

### CODE REVIEW

**Comment by otariidae** [comment]
oh...  I forgot `Destructuring assignment` is not supported by Node v4 and v5.  

By the way, `Fly` targets Node `6.x` and some plugins no longer supports Node v5 or lower.  

In my opinion, there are two ways:
- Support Node v4 and v5
or
- Drop support for Node v5 or lower

Please tell me which to choose.

**Comment by frantic1048** [comment]
Thanks for your help!

According to discussion in https://github.com/flyjs/fly/issues/242 , I prefer targeting Node 6.x.

Another way, we can keep Node v4 and v5 until April as Fly's update. Which do you prefer?

**Comment by otariidae** [comment]
@frantic1048  I prefer targeting Node v6 or later, too. :+1:

**Comment by lukeed** [comment]
We've reverted to Node 4 because of LTS. I made the mistake of dropping it too early. However, as the plugin author, you may decide what's best.

**Comment by frantic1048** [comment]
Sorry for the late, I forgot this issue for a time due to works in university. >_<
Thanks again for your work :)

**Pull request merged**
